#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Supido.Demo.Model;

namespace Supido.Demo.Model	
{
	public partial class MetaEntity
	{
		private int entityId;
		public virtual int EntityId
		{
			get
			{
				return this.entityId;
			}
			set
			{
				this.entityId = value;
			}
		}
		
		private string name;
		public virtual string Name
		{
			get
			{
				return this.name;
			}
			set
			{
				this.name = value;
			}
		}
		
		private string auditMode;
		public virtual string AuditMode
		{
			get
			{
				return this.auditMode;
			}
			set
			{
				this.auditMode = value;
			}
		}
		
		private IList<AuditTransacAction> auditTransacActions = new List<AuditTransacAction>();
		public virtual IList<AuditTransacAction> AuditTransacActions
		{
			get
			{
				return this.auditTransacActions;
			}
		}
		
	}
}
#pragma warning restore 1591
