#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Supido.Demo.Model;

namespace Supido.Demo.Model	
{
	public partial class Session
	{
		private string sessionToken;
		public virtual string SessionToken
		{
			get
			{
				return this.sessionToken;
			}
			set
			{
				this.sessionToken = value;
			}
		}
		
		private int userId;
		public virtual int UserId
		{
			get
			{
				return this.userId;
			}
			set
			{
				this.userId = value;
			}
		}
		
		private DateTime creationDttm;
		public virtual DateTime CreationDttm
		{
			get
			{
				return this.creationDttm;
			}
			set
			{
				this.creationDttm = value;
			}
		}
		
		private DateTime updateDttm;
		public virtual DateTime UpdateDttm
		{
			get
			{
				return this.updateDttm;
			}
			set
			{
				this.updateDttm = value;
			}
		}
		
		private User user;
		public virtual User User
		{
			get
			{
				return this.user;
			}
			set
			{
				this.user = value;
			}
		}
		
	}
}
#pragma warning restore 1591
