#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Supido.Demo.Model;

namespace Supido.Demo.Model	
{
	public partial class Task
	{
		private int taskId;
		public virtual int TaskId
		{
			get
			{
				return this.taskId;
			}
			set
			{
				this.taskId = value;
			}
		}
		
		private int serviceId;
		public virtual int ServiceId
		{
			get
			{
				return this.serviceId;
			}
			set
			{
				this.serviceId = value;
			}
		}
		
		private int taskTypeId;
		public virtual int TaskTypeId
		{
			get
			{
				return this.taskTypeId;
			}
			set
			{
				this.taskTypeId = value;
			}
		}
		
		private int assignedUserId;
		public virtual int AssignedUserId
		{
			get
			{
				return this.assignedUserId;
			}
			set
			{
				this.assignedUserId = value;
			}
		}
		
		private string name;
		public virtual string Name
		{
			get
			{
				return this.name;
			}
			set
			{
				this.name = value;
			}
		}
		
		private int priority;
		public virtual int Priority
		{
			get
			{
				return this.priority;
			}
			set
			{
				this.priority = value;
			}
		}
		
		private Service service;
		public virtual Service Service
		{
			get
			{
				return this.service;
			}
			set
			{
				this.service = value;
			}
		}
		
		private TaskType taskType;
		public virtual TaskType TaskType
		{
			get
			{
				return this.taskType;
			}
			set
			{
				this.taskType = value;
			}
		}
		
		private User user;
		public virtual User User
		{
			get
			{
				return this.user;
			}
			set
			{
				this.user = value;
			}
		}
		
	}
}
#pragma warning restore 1591
