#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Supido.Demo.Model;

namespace Supido.Demo.Model	
{
	public partial class User
	{
		private int userId;
		public virtual int UserId
		{
			get
			{
				return this.userId;
			}
			set
			{
				this.userId = value;
			}
		}
		
		private int departmentId;
		public virtual int DepartmentId
		{
			get
			{
				return this.departmentId;
			}
			set
			{
				this.departmentId = value;
			}
		}
		
		private string name;
		public virtual string Name
		{
			get
			{
				return this.name;
			}
			set
			{
				this.name = value;
			}
		}
		
		private string email;
		public virtual string Email
		{
			get
			{
				return this.email;
			}
			set
			{
				this.email = value;
			}
		}
		
		private string password;
		public virtual string Password
		{
			get
			{
				return this.password;
			}
			set
			{
				this.password = value;
			}
		}
		
		private Department department;
		public virtual Department Department
		{
			get
			{
				return this.department;
			}
			set
			{
				this.department = value;
			}
		}
		
		private IList<Task> tasks = new List<Task>();
		public virtual IList<Task> Tasks
		{
			get
			{
				return this.tasks;
			}
		}
		
		private IList<Session> sessions = new List<Session>();
		public virtual IList<Session> Sessions
		{
			get
			{
				return this.sessions;
			}
		}
		
		private IList<AuditTransac> auditTransacs = new List<AuditTransac>();
		public virtual IList<AuditTransac> AuditTransacs
		{
			get
			{
				return this.auditTransacs;
			}
		}
		
	}
}
#pragma warning restore 1591
